<?PHP include("config.inc"); ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>YUI Library: YUI Loader Utility</title>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="assets/reset-fonts-grids-min.css" type="text/css">
	<link rel="stylesheet" type="text/css" href="assets/dpSyntaxHighlighter.css">
	<link rel="stylesheet" type="text/css" href="assets/yui.css">
	<link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon"> 
</head>
<body id="yahoo-com" class=" yui-skin-sam">
<div id="doc3" class="yui-t7">
<div id="hd">
	<div id="ygunav">
		<p><em>
			<a href="http://developer.yahoo.com">Developer Network Home</a> <i> - </i>	
			<a href="http://help.yahoo.com/help/us/ysearch">Help</a>
			</em>
		</p>
	</div>
	<div id="ygma"><a href="/"><img src="http://l.yimg.com/a/i/us/nt/ma/ma_devnet_1.gif"  border="0"></a></div>
	<div id="pagetitle"><h1>YUI Library: YUI PHP Loader Utility</h1></div>
</div>
<div id="bd">
