<h3>YUI PHP Loader Utility Examples:</h3>

<ul>
    <li><a href='phploader-basic.php'>Using YUI PHP Loader to Load the Calendar Control (Basic)</a></li>
    <li><a href='phploader-advanced.php'>Using YUI PHP Loader to Load the Calendar Control (Advanced)</a></li>
    <li><a href='phploader-mixed-loading.php'>Mixed Loading Methods</a></li>
    <li><a href='phploader-custom-modules.php'>Adding Custom (Non-YUI) Content with YUI PHP Loader</a></li>
    <li><a href='phploader-custom-modules-with-yui.php'>Adding Custom Modules with YUI Dependencies</a></li>
    <li><a href='phploader-local-combo-handler.php'>Using the Local Combo Handler</a></li>
</ul>	
