	<h2 id="support">Support &amp; Community</h2>
	<p>The YUI Library and related topics are discussed on the on the <a href="http://groups.yahoo.com/group/ydn-javascript/">ydn-javascript</a> mailing list.</p>

	<form method="get" action="http://groups.yahoo.com/subscribe/ydn-javascript">
	<table cellspacing="0" cellpadding="2">
		<tr>
			<td align="right" width="50%"><input type="text" name="user" value="enter email address" size="20"></td>
			<td align="left"><input type="image" border="0" alt="Click here to join ydn-javascript" name="Click here to join ydn-javascript" src="http://l.yimg.com/a/i/ydn/yuiweb/img/joinbtn.gif"></td>
		</tr>
	</table>
	</form>

    <p>In addition, please visit the <a href="http://yuiblog.com">YUIBlog</a> for updates and articles about the YUI Library written by the library's developers.</p>
	
	<h2 id="filingbugs">Filing Bugs &amp; Feature Requests</h2>
	
	<p>The YUI Library's public bug tracking and feature request repositories are located on <a href="http://yuilibrary.com/projects">the YUILibrary.com site</a>.  Before filing new feature requests or bug reports, please review <a href="/yui/articles/reportingbugs/">our reporting guidelines</a>.</p>
	
